{% set version = "1.1.13" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-glmmtmb
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/glmmTMB_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/glmmTMB/glmmTMB_{{ version }}.tar.gz
  sha256: 2a94095ef4235b371978b78ef25c9338b8523e3c2cc49eaf5bd0a48ff31cde0b

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-matrix                     # [build_platform != target_platform]
    - r-rcppeigen                  # [build_platform != target_platform]
    - r-tmb                        # [build_platform != target_platform]
    - r-lme4                       # [build_platform != target_platform]
    - r-mgcv                       # [build_platform != target_platform]
    - r-nlme                       # [build_platform != target_platform]
    - r-numderiv                   # [build_platform != target_platform]
    - r-pbkrtest                   # [build_platform != target_platform]
    - r-reformulas >=0.2.0         # [build_platform != target_platform]
    - r-sandwich                   # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - libgomp                      # [not osx]
    - llvm-openmp                  # [osx]
  host:
    - r-base
    - r-matrix
    - r-rcppeigen
    - r-tmb >=1.9.0
    - r-lme4 >=1.1_18.9000
    - r-mgcv
    - r-nlme
    - r-numderiv
    - r-pbkrtest
    - r-reformulas >=0.2.0
    - r-sandwich
    - libgomp                      # [not osx]
    - llvm-openmp                  # [osx]
  run:
    - r-base
    - r-matrix
    - r-rcppeigen
    - r-tmb >=1.9.0
    - r-lme4 >=1.1_18.9000
    - r-mgcv
    - r-nlme
    - r-numderiv
    - r-pbkrtest
    - r-reformulas >=0.2.0
    - r-sandwich

test:
  commands:
    - $R -e "library('glmmTMB')"           # [not win]
    - "\"%R%\" -e \"library('glmmTMB')\""  # [win]

about:
  home: https://github.com/glmmTMB
  license: AGPL-3.0-only
  summary: Fit linear and generalized linear mixed models with various extensions, including zero-inflation. The models are fitted using maximum likelihood estimation via 'TMB' (Template Model Builder). Random effects are assumed to be Gaussian on the scale of the linear predictor and are integrated out using the Laplace
    approximation. Gradients are calculated using automatic differentiation.
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/AGPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - ccwang002
