# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Ka3UShM9Fw5skAIQIiKXOc5nGdle0i1dq/UB+xXTaWiMoMo25jiSDLGowbpcphaeKzGrgwh9nelZGsDMhYI3lXa537GSwfo4h7jxoqg21NXjYUnU7h+Jxfdxqs2fd6CegPV+Y2hLOtfHaoajUCENbCUacihsEjCE73CtPwqjPWPl+3oTNhTKA1Nwfy7HE4wMaeQBSc8ClpvZ3ZmQ5Ro6O6JXjJEg9UL8A3OLUjR3oj/J/1gaxyFcM8pilS0WOlHCE0zuO8E82OSVG5qgOa79FTvJf2ubhTQ7Ke+Ggvp4djRqGRaIQhHw7vU5YW6TM9mpRstZB59Rhs1fDXgW51C9jMzBTLQUggXAECrEGV5/E8DTY0As5Y7qJC0/qdNoi5onnEFMMC3F/5Ma5mX1MIBd4Fmm8TvyTsaOZa8JRIyfbZrq8AlTMRUyp2XUWH9gHB/NS3gwXBJOlOq9S+C0Se9D0igk3z5ExwAKDMOaFHBBrNSgYE2veNaz7lQ/qObNn5P5naJVvW56T3Z+0ccy/3dg9CfSDPQHApIcKVY/lm4bGHjdsr0Z9qG7j8KtICX4c6FX1XmWSEH7SW87eHeut7Bmr/m+RlcnyGc6ofOG8MgF1kesMhrBLB+Z2PB2rfiLvdvwFLC//QqRWRe4IloI7zU/KFsVaxrCYCr4SzCIMheNHR8="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
