appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: Ka3UShM9Fw5skAIQIiKXOc5nGdle0i1dq/UB+xXTaWiMoMo25jiSDLGowbpcphaeKzGrgwh9nelZGsDMhYI3lXa537GSwfo4h7jxoqg21NXjYUnU7h+Jxfdxqs2fd6CegPV+Y2hLOtfHaoajUCENbCUacihsEjCE73CtPwqjPWPl+3oTNhTKA1Nwfy7HE4wMaeQBSc8ClpvZ3ZmQ5Ro6O6JXjJEg9UL8A3OLUjR3oj/J/1gaxyFcM8pilS0WOlHCE0zuO8E82OSVG5qgOa79FTvJf2ubhTQ7Ke+Ggvp4djRqGRaIQhHw7vU5YW6TM9mpRstZB59Rhs1fDXgW51C9jMzBTLQUggXAECrEGV5/E8DTY0As5Y7qJC0/qdNoi5onnEFMMC3F/5Ma5mX1MIBd4Fmm8TvyTsaOZa8JRIyfbZrq8AlTMRUyp2XUWH9gHB/NS3gwXBJOlOq9S+C0Se9D0igk3z5ExwAKDMOaFHBBrNSgYE2veNaz7lQ/qObNn5P5naJVvW56T3Z+0ccy/3dg9CfSDPQHApIcKVY/lm4bGHjdsr0Z9qG7j8KtICX4c6FX1XmWSEH7SW87eHeut7Bmr/m+RlcnyGc6ofOG8MgF1kesMhrBLB+Z2PB2rfiLvdvwFLC//QqRWRe4IloI7zU/KFsVaxrCYCr4SzCIMheNHR8=}
