travis:
  secure:
    BINSTAR_TOKEN: Aau24JJtzGLSkV4iciMCnrzeAl2a31NeOUPv6VDny3bQ1BD5THMLoQzqvquBywIjL9e5E+e5nCFobu4eOlQOJgy0T6lEUk+zLCV0Eq6zLdrOhRUH6KxPD37u63PU7kErp6XDJ1DOcrafc2hgYmklIwXAFN2838ya+JpzSgq+qik9MhQoor7wp70K/ebENN0obZzO6OBI25+ZOqXHTscIg8lNC2zii7An1B1iEn84HDAkhT9N5VnjRsh4QhI7noDIQIpjCAGVz2b1U44yiGoVRZnAQZJ8JebolBanCkEHF9UJHkFD1SqZhQrP5F2nfmAIidbLJbLrCY17e3mtMOtgW354hs56tBAMJlr8THV3+6wdDUkrK5F/GxKsc7CPp6yuKfwgl98kEKDdCJDeioeobYHkQNYqFiB7+NGrU1WuJr9ls9Q90zFfgzRPpBaI0MskXJk3IC8l2O294hX8eTBuKstfr2vulBriWZvK8cLuROU9EjuR/DpeX4rf8CwA3/+xPyw41pivQZbAgMujL0AJCjY/FhHhEDtq78oGl6EMgH3x/3XihZad1fIPUWP0xcAsOXZrdkgAP4Fa+IM3RFqoJcaZz/3eCHFkKBBsZYEwwgyPhazVkJvwSjfN01sBlajc2Wm3V5jiOMWgfrhmB1gdt77ZGMjOIMC0GpN8uHoBZ7w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
